/* soapWebServiceSoapProxy.h
   Generated by gSOAP 2.8.23 from clientservice.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapWebServiceSoapProxy_H
#define soapWebServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC WebServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'WebServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in clientservice.h (non-static)
	/// Constructor
	WebServiceSoapProxy();
	/// Construct from another engine state
	WebServiceSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	WebServiceSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	WebServiceSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	WebServiceSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	WebServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor deletes deserialized data and engine context
	virtual	~WebServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void WebServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(ns1__AuthHeader *ns1__AuthHeader_);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetReportState' (returns error code or SOAP_OK)
	virtual	int GetReportState(_ns1__GetReportState *ns1__GetReportState, _ns1__GetReportStateResponse &ns1__GetReportStateResponse) { return this->GetReportState(NULL, NULL, ns1__GetReportState, ns1__GetReportStateResponse); }
	virtual	int GetReportState(const char *endpoint, const char *soap_action, _ns1__GetReportState *ns1__GetReportState, _ns1__GetReportStateResponse &ns1__GetReportStateResponse);

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login(_ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse) { return this->Login(NULL, NULL, ns1__Login, ns1__LoginResponse); }
	virtual	int Login(const char *endpoint, const char *soap_action, _ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse);

	/// Web service operation 'SyncPatientInfo' (returns error code or SOAP_OK)
	virtual	int SyncPatientInfo(_ns1__SyncPatientInfo *ns1__SyncPatientInfo, _ns1__SyncPatientInfoResponse &ns1__SyncPatientInfoResponse) { return this->SyncPatientInfo(NULL, NULL, ns1__SyncPatientInfo, ns1__SyncPatientInfoResponse); }
	virtual	int SyncPatientInfo(const char *endpoint, const char *soap_action, _ns1__SyncPatientInfo *ns1__SyncPatientInfo, _ns1__SyncPatientInfoResponse &ns1__SyncPatientInfoResponse);

	/// Web service operation 'UpdatePatientInfo' (returns error code or SOAP_OK)
	virtual	int UpdatePatientInfo(_ns1__UpdatePatientInfo *ns1__UpdatePatientInfo, _ns1__UpdatePatientInfoResponse &ns1__UpdatePatientInfoResponse) { return this->UpdatePatientInfo(NULL, NULL, ns1__UpdatePatientInfo, ns1__UpdatePatientInfoResponse); }
	virtual	int UpdatePatientInfo(const char *endpoint, const char *soap_action, _ns1__UpdatePatientInfo *ns1__UpdatePatientInfo, _ns1__UpdatePatientInfoResponse &ns1__UpdatePatientInfoResponse);

	/// Web service operation 'SyncDataState' (returns error code or SOAP_OK)
	virtual	int SyncDataState(_ns1__SyncDataState *ns1__SyncDataState, _ns1__SyncDataStateResponse &ns1__SyncDataStateResponse) { return this->SyncDataState(NULL, NULL, ns1__SyncDataState, ns1__SyncDataStateResponse); }
	virtual	int SyncDataState(const char *endpoint, const char *soap_action, _ns1__SyncDataState *ns1__SyncDataState, _ns1__SyncDataStateResponse &ns1__SyncDataStateResponse);

	/// Web service operation 'UpdateDataState' (returns error code or SOAP_OK)
	virtual	int UpdateDataState(_ns1__UpdateDataState *ns1__UpdateDataState, _ns1__UpdateDataStateResponse &ns1__UpdateDataStateResponse) { return this->UpdateDataState(NULL, NULL, ns1__UpdateDataState, ns1__UpdateDataStateResponse); }
	virtual	int UpdateDataState(const char *endpoint, const char *soap_action, _ns1__UpdateDataState *ns1__UpdateDataState, _ns1__UpdateDataStateResponse &ns1__UpdateDataStateResponse);

	/// Web service operation 'SyncReportState' (returns error code or SOAP_OK)
	virtual	int SyncReportState(_ns1__SyncReportState *ns1__SyncReportState, _ns1__SyncReportStateResponse &ns1__SyncReportStateResponse) { return this->SyncReportState(NULL, NULL, ns1__SyncReportState, ns1__SyncReportStateResponse); }
	virtual	int SyncReportState(const char *endpoint, const char *soap_action, _ns1__SyncReportState *ns1__SyncReportState, _ns1__SyncReportStateResponse &ns1__SyncReportStateResponse);

	/// Web service operation 'UploadFile' (returns error code or SOAP_OK)
	virtual	int UploadFile(_ns1__UploadFile *ns1__UploadFile, _ns1__UploadFileResponse &ns1__UploadFileResponse) { return this->UploadFile(NULL, NULL, ns1__UploadFile, ns1__UploadFileResponse); }
	virtual	int UploadFile(const char *endpoint, const char *soap_action, _ns1__UploadFile *ns1__UploadFile, _ns1__UploadFileResponse &ns1__UploadFileResponse);

	/// Web service operation 'GetQuery' (returns error code or SOAP_OK)
	virtual	int GetQuery(_ns1__GetQuery *ns1__GetQuery, _ns1__GetQueryResponse &ns1__GetQueryResponse) { return this->GetQuery(NULL, NULL, ns1__GetQuery, ns1__GetQueryResponse); }
	virtual	int GetQuery(const char *endpoint, const char *soap_action, _ns1__GetQuery *ns1__GetQuery, _ns1__GetQueryResponse &ns1__GetQueryResponse);

	/// Web service operation 'UpdateQuery' (returns error code or SOAP_OK)
	virtual	int UpdateQuery(_ns1__UpdateQuery *ns1__UpdateQuery, _ns1__UpdateQueryResponse &ns1__UpdateQueryResponse) { return this->UpdateQuery(NULL, NULL, ns1__UpdateQuery, ns1__UpdateQueryResponse); }
	virtual	int UpdateQuery(const char *endpoint, const char *soap_action, _ns1__UpdateQuery *ns1__UpdateQuery, _ns1__UpdateQueryResponse &ns1__UpdateQueryResponse);

	/// Web service operation 'GetReportState' (returns error code or SOAP_OK)
	virtual	int GetReportState_(_ns1__GetReportState *ns1__GetReportState, _ns1__GetReportStateResponse &ns1__GetReportStateResponse) { return this->GetReportState_(NULL, NULL, ns1__GetReportState, ns1__GetReportStateResponse); }
	virtual	int GetReportState_(const char *endpoint, const char *soap_action, _ns1__GetReportState *ns1__GetReportState, _ns1__GetReportStateResponse &ns1__GetReportStateResponse);

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login_(_ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse) { return this->Login_(NULL, NULL, ns1__Login, ns1__LoginResponse); }
	virtual	int Login_(const char *endpoint, const char *soap_action, _ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse);

	/// Web service operation 'SyncPatientInfo' (returns error code or SOAP_OK)
	virtual	int SyncPatientInfo_(_ns1__SyncPatientInfo *ns1__SyncPatientInfo, _ns1__SyncPatientInfoResponse &ns1__SyncPatientInfoResponse) { return this->SyncPatientInfo_(NULL, NULL, ns1__SyncPatientInfo, ns1__SyncPatientInfoResponse); }
	virtual	int SyncPatientInfo_(const char *endpoint, const char *soap_action, _ns1__SyncPatientInfo *ns1__SyncPatientInfo, _ns1__SyncPatientInfoResponse &ns1__SyncPatientInfoResponse);

	/// Web service operation 'UpdatePatientInfo' (returns error code or SOAP_OK)
	virtual	int UpdatePatientInfo_(_ns1__UpdatePatientInfo *ns1__UpdatePatientInfo, _ns1__UpdatePatientInfoResponse &ns1__UpdatePatientInfoResponse) { return this->UpdatePatientInfo_(NULL, NULL, ns1__UpdatePatientInfo, ns1__UpdatePatientInfoResponse); }
	virtual	int UpdatePatientInfo_(const char *endpoint, const char *soap_action, _ns1__UpdatePatientInfo *ns1__UpdatePatientInfo, _ns1__UpdatePatientInfoResponse &ns1__UpdatePatientInfoResponse);

	/// Web service operation 'SyncDataState' (returns error code or SOAP_OK)
	virtual	int SyncDataState_(_ns1__SyncDataState *ns1__SyncDataState, _ns1__SyncDataStateResponse &ns1__SyncDataStateResponse) { return this->SyncDataState_(NULL, NULL, ns1__SyncDataState, ns1__SyncDataStateResponse); }
	virtual	int SyncDataState_(const char *endpoint, const char *soap_action, _ns1__SyncDataState *ns1__SyncDataState, _ns1__SyncDataStateResponse &ns1__SyncDataStateResponse);

	/// Web service operation 'UpdateDataState' (returns error code or SOAP_OK)
	virtual	int UpdateDataState_(_ns1__UpdateDataState *ns1__UpdateDataState, _ns1__UpdateDataStateResponse &ns1__UpdateDataStateResponse) { return this->UpdateDataState_(NULL, NULL, ns1__UpdateDataState, ns1__UpdateDataStateResponse); }
	virtual	int UpdateDataState_(const char *endpoint, const char *soap_action, _ns1__UpdateDataState *ns1__UpdateDataState, _ns1__UpdateDataStateResponse &ns1__UpdateDataStateResponse);

	/// Web service operation 'SyncReportState' (returns error code or SOAP_OK)
	virtual	int SyncReportState_(_ns1__SyncReportState *ns1__SyncReportState, _ns1__SyncReportStateResponse &ns1__SyncReportStateResponse) { return this->SyncReportState_(NULL, NULL, ns1__SyncReportState, ns1__SyncReportStateResponse); }
	virtual	int SyncReportState_(const char *endpoint, const char *soap_action, _ns1__SyncReportState *ns1__SyncReportState, _ns1__SyncReportStateResponse &ns1__SyncReportStateResponse);

	/// Web service operation 'UploadFile' (returns error code or SOAP_OK)
	virtual	int UploadFile_(_ns1__UploadFile *ns1__UploadFile, _ns1__UploadFileResponse &ns1__UploadFileResponse) { return this->UploadFile_(NULL, NULL, ns1__UploadFile, ns1__UploadFileResponse); }
	virtual	int UploadFile_(const char *endpoint, const char *soap_action, _ns1__UploadFile *ns1__UploadFile, _ns1__UploadFileResponse &ns1__UploadFileResponse);

	/// Web service operation 'GetQuery' (returns error code or SOAP_OK)
	virtual	int GetQuery_(_ns1__GetQuery *ns1__GetQuery, _ns1__GetQueryResponse &ns1__GetQueryResponse) { return this->GetQuery_(NULL, NULL, ns1__GetQuery, ns1__GetQueryResponse); }
	virtual	int GetQuery_(const char *endpoint, const char *soap_action, _ns1__GetQuery *ns1__GetQuery, _ns1__GetQueryResponse &ns1__GetQueryResponse);

	/// Web service operation 'UpdateQuery' (returns error code or SOAP_OK)
	virtual	int UpdateQuery_(_ns1__UpdateQuery *ns1__UpdateQuery, _ns1__UpdateQueryResponse &ns1__UpdateQueryResponse) { return this->UpdateQuery_(NULL, NULL, ns1__UpdateQuery, ns1__UpdateQueryResponse); }
	virtual	int UpdateQuery_(const char *endpoint, const char *soap_action, _ns1__UpdateQuery *ns1__UpdateQuery, _ns1__UpdateQueryResponse &ns1__UpdateQueryResponse);
};
#endif
